### ISSUE TITLE
No component found with scheme: mycomponent

### ISSUE THREAD

**Issue by dmhumph1547** [gpe-mw-training/camel-labs#5]
When trying to run a maven install in JBoss Developer Studio I am unable to complete the build successfully due to the following error:

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.548 sec <<< FAILURE! - in com.redhat.gpe.training.camel.MyComponentTest
testMyComponent(com.redhat.gpe.training.camel.MyComponentTest)  Time elapsed: 0.506 sec  <<< ERROR!
org.apache.camel.FailedToCreateRouteException: Failed to create route route1: Route(route1)[[From[mycomponent://foo]] -> [To[mycomponent:/... because of Failed to resolve endpoint: mycomponent://foo due to: No component found with scheme: mycomponent
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:182)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:778)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:1955)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:1705)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:1579)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:1547)
	at org.apache.camel.test.junit4.CamelTestSupport.startCamelContext(CamelTestSupport.java:477)
	at org.apache.camel.test.junit4.CamelTestSupport.doSetUp(CamelTestSupport.java:311)
	at org.apache.camel.test.junit4.CamelTestSupport.setUp(CamelTestSupport.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: org.apache.camel.ResolveEndpointFailedException: Failed to resolve endpoint: mycomponent://foo due to: No component found with scheme: mycomponent
	at org.apache.camel.impl.DefaultCamelContext.getEndpoint(DefaultCamelContext.java:537)
	at org.apache.camel.util.CamelContextHelper.getMandatoryEndpoint(CamelContextHelper.java:71)
	at org.apache.camel.model.RouteDefinition.resolveEndpoint(RouteDefinition.java:192)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:106)
	at org.apache.camel.impl.DefaultRouteContext.resolveEndpoint(DefaultRouteContext.java:112)
	at org.apache.camel.model.FromDefinition.resolveEndpoint(FromDefinition.java:72)
	at org.apache.camel.impl.DefaultRouteContext.getEndpoint(DefaultRouteContext.java:88)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:890)
	at org.apache.camel.model.RouteDefinition.addRoutes(RouteDefinition.java:177)
	at org.apache.camel.impl.DefaultCamelContext.startRoute(DefaultCamelContext.java:778)
	at org.apache.camel.impl.DefaultCamelContext.startRouteDefinitions(DefaultCamelContext.java:1955)
	at org.apache.camel.impl.DefaultCamelContext.doStartCamel(DefaultCamelContext.java:1705)
	at org.apache.camel.impl.DefaultCamelContext.doStart(DefaultCamelContext.java:1579)
	at org.apache.camel.support.ServiceSupport.start(ServiceSupport.java:61)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:1547)
	at org.apache.camel.test.junit4.CamelTestSupport.startCamelContext(CamelTestSupport.java:477)
	at org.apache.camel.test.junit4.CamelTestSupport.doSetUp(CamelTestSupport.java:311)
	at org.apache.camel.test.junit4.CamelTestSupport.setUp(CamelTestSupport.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Results :

Tests in error: 
  MyComponentTest>CamelTestSupport.setUp:217->CamelTestSupport.doSetUp:311->CamelTestSupport.startCamelContext:477 » FailedToCreateRoute

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] RedHat GPE Training :: Camel Project Exercise ...... SUCCESS [  0.292 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 2 :: Simple . SUCCESS [  5.915 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: Project  SUCCESS [  0.017 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: DataFormat SUCCESS [  0.707 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: Exceptions SUCCESS [  0.069 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: Expressions SUCCESS [  0.140 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: TypeConverter SUCCESS [  0.349 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 3 :: Threads  SUCCESS [  0.163 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 4 :: Project  SUCCESS [  0.012 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 4 :: Spring Standalone SUCCESS [  0.063 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 4 :: Java Standalone SUCCESS [  0.118 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 4 :: Unit Test SUCCESS [  1.132 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 4 :: Spring Web SUCCESS [  2.134 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 5 :: Project  SUCCESS [  0.012 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 5 :: Webservice SUCCESS [  3.359 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 5 :: SQL .... SUCCESS [  0.077 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 5 :: RESTFull client SUCCESS [  0.168 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 6 :: Project  SUCCESS [  0.061 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 6 :: Aggregator SUCCESS [  1.170 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 6 :: CBR .... SUCCESS [  0.934 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 6 :: Enricher SUCCESS [  0.973 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 6 :: Recipient List SUCCESS [  0.830 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: Project  SUCCESS [  0.017 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: JDBC JMS Transacted Route SUCCESS [  3.828 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: JMS Tx Client SUCCESS [  2.167 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: MyComponent FAILURE [  2.736 s]
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: RoutePolicy SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 7 :: Security SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Project SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Plain Old Java Jar SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Greeter Service SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Greeter Client SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Camel Blueprint SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Camel Unit Test using PojoSR framework SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 8 :: OSGi :: Camel Unit Test with OPS4J Pax Exam SKIPPED
[INFO] A Camel Blueprint Route ............................ SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 9 :: Project  SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 9 :: Fabric Camel Rest SKIPPED
[INFO] RedHat GPE Training :: Camel :: Lab :: 9 :: Fabric Camel Twitter SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.403 s
[INFO] Finished at: 2015-11-19T14:14:59-06:00
[INFO] Final Memory: 63M/472M

**Comment by honghuac** [comment]
Hi

This isn't the right forum to discuss errors encountered during eLab training. I am closing this issue.
Please raise this issue within Red Hat Skills Exchange / Partner Connect, thanks.
